### PR TITLE
Image downloading for Products and Skus

### PR DESCRIPTION
**Pull request by brxck**
As discussed in #8, this implements image downloading for Products, Skus, and the expanded product objects on Skus.

Downloading needs to be enabled with `downloadFiles: true` in the options object.

The Gatsby File nodes are referenced in the `localFiles` field.

```
{
  allStripeSku {
    edges {
      node {
        localFiles {
          id
        }
        product {
          localFiles {
            id
          }
        }
      }
    }
  }
}
```

I also want to implement this for Files, which shouldn't take much, but I wanted to see what you think of this implementation first, @njosefbeck! Any feedback is appreciated :+1:

### CODE REVIEW

**Comment by njosefbeck** [comment]
@brxck Awesome first iteration! I haven't had a chance yet to really test the implementation, and I'm sure I'll have more to say, but a couple of things that initially stand out:

- Verify that you have the latest from my master
- Move gatsby-source-filesystem from a peerDependency to a regular dependency. We do this since you're requiring this dependency in the code and so it's needed for running the plugin.
- Ideally a lot of the implementation code would live on a class of some kind (either StripeObject or another, maybe a "File" class). When I dig deeper into your implementation, I'm sure I'll have more to say in this area, but feel free to take a stab at that.

Looking forward to diving in deeper! Let me know if you make changes and I can pull them down locally for testing.

**Comment by brxck** [comment]
- I think you're right about the dependency actually. I was imitating something I had seen in other plugins, but those were transformer plugins which don't actually rely on code from gatsby-source-filesystem. Thinking about it now, it makes more sense to make it a regular dependency.
- Definitely want to move the code out of gatsby-node, but I wasn't exactly sure the best place to put it. A new class sounds like a good idea though.
- I have it working in a project right now actually, but I think I see the problem: Product images are being processed, but at some point I started missing the Sku `image` field. Hopefully that's what you're running into? Gonna have to fix that...

Thanks for looking at it! I'll keep you posted as I work on these things.

**Comment by njosefbeck** [comment]
Yeah, I'm imagining a class called "ImageFile" or something, where all the functionality can live, but up to you as far as how you'd want to name it.

And as far as it not working for me. I didn't get any errors in the console when I ran `npm run develop` to spin up the Gatsby server, but when I try to query for localFiles in GraphiQL it doesn't find the field.

screen shot 2018-11-28 at 1 27 15 pm

I haven't walked through the code step-by-step yet to maybe see what the issue is. Will update you as I dive deeper!

**Comment by brxck** [comment]
Hmm that's troubling. I would make a wild guess that createRemoteFileNode is erroring out and it's getting swallowed up by the try/catch it's wrapped in.

Speaking of, what's the best way to handle those errors when they happen? I know it's generally bad form to catch exceptions and just throw them away, but every plugin I've seen does just that with createRemoteFileNode.

**Comment by brxck** [comment]
This last commit might fix the issue you're having! Single images weren't being processed properly, but now I have both sku and product images working in the project I've been testing on.

**Comment by njosefbeck** [comment]
So allStripeSku is now showing the localFiles field for me, which is great! My test products don't have images so I'm not able to test that, but I'll assume it'll work.

As far as properly handling errors in this particular try {...} catch {...} block, you're right that the error is probably swallowed up in gatsby-source-filesystem. If you look in that plugin's source code, they don't seem to log or throw their errors. If they threw an error, then your catch block could catch it, and display it / do something with it. I think that's how it would work anyway. 

I think it can't hurt to stick a console.log statement there like you're doing, in case the underlying plugin function code changes later and they start throwing errors.

So it seems like next steps would be:
- Move that dependency to "dependencies" in package.json
- Move code out of gatsby-node into its own class
- Add explanation of how to use the feature in the README. Also include motivation for using (i.e. explain how you could leverage this feature + gatsby-transformer-sharp to get those optimized images - I think this is something one could do?)

Once we add this feature to the plugin, we can look into adding this functionality to the File Stripe type. We might have to tackle "File" not being an iterable list for some reason... I can explain this a bit more when the time comes.

Thanks again for all your hard work!

**Comment by brxck** [comment]
Alright.

- I've moved the functionality into the LocalFile class. To me it feels sort of clumsy, but I'm not sure.
- gatsby-source-filesystem is now a regular dependency.
- And I've done my best to document purpose and usage of this feature in a few points of the readme.

Happy to be contributing! Thanks for the guidance.

**Comment by njosefbeck** [comment]
Awesome! I'll take a look over the weekend. :)

**Comment by brxck** [comment]
I see what you're saying about the README, but for those plugins no extra configuration is needed to use our Files nodes. They only need to be queried either through their Stripe nodes, which we document, or as one would query any other Gatsby node. From there, gatsby-image and gatsby-plugin-sharp document how they can use those nodes. So as far as I can see, there isn't much more to document on our end, but let me know if there's more I can do to bridge that gap.

Looking at it now, I'm going to change change my link from transformer-sharp to plugin-sharp, which has more of the documentation I mean to reference.

Glad it's looking good to you! Thanks again.

**Comment by njosefbeck** [comment]
That makes sense to me! Once you swap out that link, I'll then merge your code into master :).

**Comment by brxck** [comment]
Actually I just looked again and I think it's good to go as is 😅 The README for the plugin is pretty sparse but they've got a good example site that I'm already linking to.

**Pull request merged**
