### PR TITLE
Download files for Prices' Products

### PR DESCRIPTION
**Pull request by brxck**
Hey, hope you are doing well!

Very small change to enable downloading of images in the expanded `products` field of the Price type. This is the same as doing it for the Sku type.

I marked this as WIP because I wanted to know your opinion on if/how the tests and the `extractSkuUrls` name should change to accommodate this.

### CODE REVIEW

**Comment by njosefbeck** [comment]
Hi! Nice to hear from you!

I guess we could rename the `extractSkuUrls` to be more generic, i.e. `extractUrls` ? I'd have to look at the tests again to see how they might need to change, but whatever you think is best I'll probably agree with!

**Comment by clemgrim** [comment]
hello @njosefbeck, any updates on this? Thank you!

**Comment by njosefbeck** [comment]
@brxck If you want to make the above name changes, I can merge this this weekend!

@clemgrim once brxck makes the above changes, I'll work on getting this merge and published to npm. Might still be a couple weeks, depending on schedules, etc. Appreciate your patience!

**Comment by michalien** [comment]
Hi @njosefbeck - any update? Many thanks, Mike

**Comment by njosefbeck** [comment]
@michalien no updates on my end! @brxck any updates on your end?

**Comment by brxck** [comment]
Unfortunately not! To copy from the other issue:

> Sorry for the delay, but as things currently stand I'll be unable to make any changes for some time. 
> 
> Please feel free to make any changes required to get this merged.

**Review by njosefbeck — APPROVED** [review]
This all looks good to me! If you feel good about it, I can go ahead and merge it and publish it this week. I also imagine some of the dependencies should be updated -- if you have time to do that, would be appreciated. Otherwise I can look into it! Thanks!

**Comment by brxck** [comment]
@njosefbeck please take a look when you can.

`extractSkuUrls` has become `extractChildUrls`, since `extractUrls` already exists.

Prices/Skus are identically shaped for the purpose of grabbing images, so tests have just been modified to swap out the object type in order to test both.

**Comment by brxck** [comment]
Nice timing! I'm catching up on a lot so I'll leave deps to you. Thanks!

**Pull request merged**
